/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Swing;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author felip
 */
public class Main extends JFrame {

    
    public Main() {
        initComponents();
        
        this.setLocationRelativeTo(this);
        this.pintarImagen(this.lblFondo, "src/main/java/Vista/Imagenes/paisaje_1024x768.png");
        this.pintarImagen(this.gato_lucas, "src/main/java/Vista/Imagenes/lucas.png");
        this.pintarImagen(this.gato_silueta, "src/main/java/Vista/Imagenes/silueta.png");
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alerta = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        alertaBtn = new javax.swing.JButton();
        contenido = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        introduccion1 = new javax.swing.JLabel();
        introduccion2 = new javax.swing.JLabel();
        gato_lucas = new javax.swing.JLabel();
        gato_silueta = new javax.swing.JLabel();
        iniciarBtn = new javax.swing.JButton();
        jugador = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        alerta.setTitle("Ingresar nombre");
        alerta.setSize(new java.awt.Dimension(600, 300));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡INGRESA TU NOMBRE!");

        alertaBtn.setText("Aceptar");
        alertaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alertaLayout = new javax.swing.GroupLayout(alerta.getContentPane());
        alerta.getContentPane().setLayout(alertaLayout);
        alertaLayout.setHorizontalGroup(
            alertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alertaLayout.createSequentialGroup()
                .addGroup(alertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alertaLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(alertaLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(alertaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        alertaLayout.setVerticalGroup(
            alertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alertaLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(alertaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("La travesia de Lucas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Informal Roman", 0, 70)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 255, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("La travesia de Lucas");
        contenido.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 570, 96));

        introduccion1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        introduccion1.setForeground(new java.awt.Color(0, 0, 0));
        introduccion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        introduccion1.setText("¡Lucas necesita tu ayuda!");
        contenido.add(introduccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 440, 60));

        introduccion2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        introduccion2.setForeground(new java.awt.Color(0, 0, 0));
        introduccion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        introduccion2.setText("¿Cual es tu nombre, jugador?");
        contenido.add(introduccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 430, 60));
        contenido.add(gato_lucas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 170, 320));
        contenido.add(gato_silueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 170, 320));

        iniciarBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        iniciarBtn.setForeground(new java.awt.Color(0, 0, 0));
        iniciarBtn.setText("Iniciar aventura");
        iniciarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarBtnActionPerformed(evt);
            }
        });
        contenido.add(iniciarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, 280, 70));

        jugador.setBackground(new java.awt.Color(255, 255, 255));
        contenido.add(jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 320, 40));

        lblFondo.setBackground(new java.awt.Color(255, 255, 255));
        contenido.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 770));

        getContentPane().add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarBtnActionPerformed
        if (jugador.getText().equals("")) {
            alerta.setLocationRelativeTo(this);
            alerta.setVisible(true);
        } else {
            P1 p1 = new P1(jugador.getText());
            mostrarPanel(p1);
        }
        
        
    }//GEN-LAST:event_iniciarBtnActionPerformed

    private void alertaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertaBtnActionPerformed
        alerta.setVisible(false);
    }//GEN-LAST:event_alertaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    public static void pintarImagen(JLabel lbl, String ruta) {
        ImageIcon imagen = new ImageIcon(ruta);;
        Icon icono  = new ImageIcon(imagen.getImage().getScaledInstance(
                lbl.getWidth(), 
                lbl.getHeight(), 
                Image.SCALE_DEFAULT)
        );
        lbl.setIcon(icono);
    }

    public static void mostrarPanel(JPanel panel) {
        panel.setSize(1024, 768);
        panel.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        contenido.revalidate();
        contenido.repaint();
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog alerta;
    private javax.swing.JButton alertaBtn;
    private static javax.swing.JPanel contenido;
    private javax.swing.JLabel gato_lucas;
    private javax.swing.JLabel gato_silueta;
    private javax.swing.JButton iniciarBtn;
    private javax.swing.JLabel introduccion1;
    private javax.swing.JLabel introduccion2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jugador;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
