/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Swing;

import java.awt.Color;
import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author felip
 */
public class P1 extends javax.swing.JPanel {
    public static String jugador;
    private String introduccion;
    
    public P1(String jugador) {
        this.jugador = jugador;
        this.introduccion = "Lucas es un gato que vive en un bosque muy \npeculiar, le llaman 'El pozo'. A veces recorrer \neste raro lugar le resulta muy complicado, asi \nque Lucas esta decidido en comprarse un \ncarro todoterreno. \n" + this.jugador + ", \n¡Acompaña a Lucas en esta aventura!";
        initComponents();
        fondo.setSize(1024, 768);
        lucas.setSize(180, 300);
        texto.setText(this.introduccion);
        texto.setBackground(new Color(0, 0, 0, 1));
        Main.pintarImagen(fondo, "src/main/java/Vista/Imagenes/pozo.png");
        Main.pintarImagen(lucas, "src/main/java/Vista/Imagenes/lucas.png");
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        continuarBtn = new javax.swing.JButton();
        lucas = new javax.swing.JLabel();
        texto = new javax.swing.JTextArea();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Informal Roman", 0, 70)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 255, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("La travesia de Lucas");
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 570, 96));

        continuarBtn.setText("Continuar");
        continuarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarBtnActionPerformed(evt);
            }
        });
        add(continuarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 250, 60));
        add(lucas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 180, 300));

        texto.setEditable(false);
        texto.setColumns(20);
        texto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setRows(5);
        texto.setText("Lucas es un gato que vive en un bosque muy \npeculiar, le llaman “El Pozo”. A veces recorrer \neste raro lugar le resulta muy complicado, así \nque Lucas está decidido en comprarse un \ncarro todoterreno.  \nJugador, ¡Acompaña a Lucas en esta aventura!");
        texto.setBorder(null);
        add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, 170));

        fondo.setMaximumSize(new java.awt.Dimension(1024, 768));
        fondo.setPreferredSize(new java.awt.Dimension(1024, 768));
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));
    }// </editor-fold>//GEN-END:initComponents

    private void continuarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarBtnActionPerformed
        P2 p2 = new P2();
        Main.mostrarPanel(p2);
    }//GEN-LAST:event_continuarBtnActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuarBtn;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lucas;
    private javax.swing.JTextArea texto;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
