/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Swing;

import java.awt.Color;
import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author felip
 */
public class P2 extends javax.swing.JPanel {

    
    public P2() {
        initComponents();
        texto1.setBackground(new Color(0, 0, 0, 1));
        texto2.setBackground(new Color(0, 0, 0, 1));
        fondo.setSize(1024, 768);
        Main.pintarImagen(fondo, "src/main/java/Vista/Imagenes/pozo.png");
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        continuarBtn = new javax.swing.JButton();
        texto1 = new javax.swing.JTextArea();
        texto2 = new javax.swing.JTextArea();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Informal Roman", 0, 70)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 255, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Un viaje tranquilo... ¿o no?");
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 720, 96));

        continuarBtn.setText("Continuar");
        continuarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarBtnActionPerformed(evt);
            }
        });
        add(continuarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 250, 60));

        texto1.setEditable(false);
        texto1.setColumns(20);
        texto1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto1.setForeground(new java.awt.Color(255, 255, 255));
        texto1.setRows(5);
        texto1.setText("Lucas, el gato, era conocido \nen todo el Bosque del Pozo \npor su curiosidad infinita y su \ntendencia a meterse en \nproblemas. Vivía en una \npequeña cabaña en lo más \nprofundo del bosque, \nrodeado de árboles altísimos \ny criaturas misteriosas.");
        texto1.setBorder(null);
        add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 220));

        texto2.setEditable(false);
        texto2.setColumns(20);
        texto2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto2.setForeground(new java.awt.Color(255, 255, 255));
        texto2.setRows(5);
        texto2.setText("Contento por tu compañia, \nLucas emprende el viaje a \n‘Concesionario El Minino’ \npara comprar su tan \nanhelado carro.\n¿Sera este un viaje tranquilo?");
        texto2.setBorder(null);
        add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, -1, 170));
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));
    }// </editor-fold>//GEN-END:initComponents

    private void continuarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarBtnActionPerformed
        P3 p3 = new P3();
        Main.mostrarPanel(p3);
    }//GEN-LAST:event_continuarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuarBtn;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextArea texto1;
    private javax.swing.JTextArea texto2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
