/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Swing;

import java.awt.event.KeyEvent;

/**
 *
 * @author felip
 */
public class P5 extends javax.swing.JPanel {

    PanelJuego snake;
    public static int puntuacion;
    
    public P5() {
        initComponents();
        fondo.setSize(1024, 768);
        Main.pintarImagen(fondo, "src/main/java/Vista/Imagenes/pozo.png");
        
        snake = new PanelJuego();
        snake.setSize(500, 500);
        juego.add(snake);
        juego.pack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reintentarBtn = new javax.swing.JButton();
        juego = new javax.swing.JInternalFrame();
        texto = new javax.swing.JLabel();
        continuarBtn = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reintentarBtn.setText("Reintentar");
        reintentarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reintentarBtnActionPerformed(evt);
            }
        });
        add(reintentarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 250, 60));

        juego.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        juego.setVisible(true);

        javax.swing.GroupLayout juegoLayout = new javax.swing.GroupLayout(juego.getContentPane());
        juego.getContentPane().setLayout(juegoLayout);
        juegoLayout.setHorizontalGroup(
            juegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        juegoLayout.setVerticalGroup(
            juegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 520, 540));

        texto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto.setText("¡Consigue al menos 5 puntos!");
        add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 330, 110));

        continuarBtn.setText("Continuar");
        continuarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarBtnActionPerformed(evt);
            }
        });
        add(continuarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 250, 60));
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));
    }// </editor-fold>//GEN-END:initComponents

    private void reintentarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reintentarBtnActionPerformed
        if (snake.perdido) {
            snake.reiniciarEstado();
            snake.jugar();
            
        }
    }//GEN-LAST:event_reintentarBtnActionPerformed

    private void continuarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarBtnActionPerformed
        if (!snake.perdido) {
            puntuacion = snake.puntos;
            P6 p6 = new P6();
            Main.mostrarPanel(p6);
            
        }
    }//GEN-LAST:event_continuarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuarBtn;
    private javax.swing.JLabel fondo;
    private javax.swing.JInternalFrame juego;
    private javax.swing.JButton reintentarBtn;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
