/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Swing;

import java.awt.Color;

/**
 *
 * @author felip
 */
public class P6 extends javax.swing.JPanel {

    /**
     * Creates new form P6
     */
    public P6() {
        initComponents();
        fondo.setSize(1024, 768);
        texto.setBackground(new Color(0, 0, 0, 1));
        serpentina.setSize(300, 300);
        Main.pintarImagen(fondo, "src/main/java/Vista/Imagenes/pozo.png");
        Main.pintarImagen(serpentina, "src/main/java/Vista/Imagenes/serpentina.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        serpentina = new javax.swing.JLabel();
        continuarBtn = new javax.swing.JButton();
        texto = new javax.swing.JTextArea();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Informal Roman", 0, 70)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 255, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Concesionario");
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 720, 96));
        add(serpentina, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 300, 300));

        continuarBtn.setText("Continuar");
        continuarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarBtnActionPerformed(evt);
            }
        });
        add(continuarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 250, 60));

        texto.setEditable(false);
        texto.setColumns(20);
        texto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setRows(5);
        texto.setText("Serpentina está muy agradecida por la \nayuda. Para agradecerles, los guia hacía el\nconcesionario \"El Minino\". ¡Por fin!\nLucas está muy feliz.");
        texto.setBorder(null);
        add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 350, 150));
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));
    }// </editor-fold>//GEN-END:initComponents

    private void continuarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarBtnActionPerformed
        P7 p7 = new P7();
        Main.mostrarPanel(p7);
    }//GEN-LAST:event_continuarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuarBtn;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel serpentina;
    private javax.swing.JTextArea texto;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
