/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Swing;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author felip
 */
public class Main extends JFrame {

    
    public Main() {
        initComponents();
        
        setLocationRelativeTo(this);
        paintImage(backgroundImg, new int[]{1024, 768}, "src/main/java/View/Images/landscape.png");
        paintImage(lucasImg, new int[]{170, 320}, "src/main/java/View/Images/lucas.png");
        paintImage(silhouetteImg, new int[]{170, 320}, "src/main/java/View/Images/silhouette.png");
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alertDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        alertBtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        titleTxt = new javax.swing.JLabel();
        intro1Txt = new javax.swing.JLabel();
        intro2Txt = new javax.swing.JLabel();
        lucasImg = new javax.swing.JLabel();
        silhouetteImg = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();
        playerTxtfield = new javax.swing.JTextField();
        backgroundImg = new javax.swing.JLabel();

        alertDialog.setTitle("Ingresar nombre");
        alertDialog.setSize(new java.awt.Dimension(600, 300));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡INGRESA TU NOMBRE!");

        alertBtn.setText("Aceptar");
        alertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alertDialogLayout = new javax.swing.GroupLayout(alertDialog.getContentPane());
        alertDialog.getContentPane().setLayout(alertDialogLayout);
        alertDialogLayout.setHorizontalGroup(
            alertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alertDialogLayout.createSequentialGroup()
                .addGroup(alertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alertDialogLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(alertDialogLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(alertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        alertDialogLayout.setVerticalGroup(
            alertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alertDialogLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(alertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("La travesia de Lucas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleTxt.setFont(new java.awt.Font("Informal Roman", 0, 70)); // NOI18N
        titleTxt.setForeground(new java.awt.Color(0, 255, 0));
        titleTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTxt.setText("La travesia de Lucas");
        contentPanel.add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 570, 96));

        intro1Txt.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        intro1Txt.setForeground(new java.awt.Color(0, 0, 0));
        intro1Txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        intro1Txt.setText("¡Lucas necesita tu ayuda!");
        contentPanel.add(intro1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 440, 60));

        intro2Txt.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        intro2Txt.setForeground(new java.awt.Color(0, 0, 0));
        intro2Txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        intro2Txt.setText("¿Cual es tu nombre, jugador?");
        contentPanel.add(intro2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 430, 60));
        contentPanel.add(lucasImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 170, 320));
        contentPanel.add(silhouetteImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 170, 320));

        startBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        startBtn.setForeground(new java.awt.Color(0, 0, 0));
        startBtn.setText("Iniciar aventura");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });
        contentPanel.add(startBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, 280, 70));

        playerTxtfield.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.add(playerTxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 320, 40));

        backgroundImg.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.add(backgroundImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        if (playerTxtfield.getText().equals("")) {
            alertDialog.setLocationRelativeTo(this);
            alertDialog.setVisible(true);
        } else {
            P1 p1 = new P1(playerTxtfield.getText());
            showPanel(p1);
        }
        
        
    }//GEN-LAST:event_startBtnActionPerformed

    private void alertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertBtnActionPerformed
        alertDialog.setVisible(false);
    }//GEN-LAST:event_alertBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    public static void paintImage(JLabel lbl, int size[], String path) {
        lbl.setSize(size[0], size[1]);
        ImageIcon image = new ImageIcon(path);
        Icon icon  = new ImageIcon(image.getImage().getScaledInstance(
                lbl.getWidth(), 
                lbl.getHeight(), 
                Image.SCALE_DEFAULT)
        );
        lbl.setIcon(icon);
    }

    public static void showPanel(JPanel panel) {
        panel.setSize(1024, 768);
        panel.setLocation(0, 0);
        
        contentPanel.removeAll();
        contentPanel.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        contentPanel.revalidate();
        contentPanel.repaint();
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alertBtn;
    private javax.swing.JDialog alertDialog;
    private javax.swing.JLabel backgroundImg;
    private static javax.swing.JPanel contentPanel;
    private javax.swing.JLabel intro1Txt;
    private javax.swing.JLabel intro2Txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lucasImg;
    private javax.swing.JTextField playerTxtfield;
    private javax.swing.JLabel silhouetteImg;
    private javax.swing.JButton startBtn;
    private javax.swing.JLabel titleTxt;
    // End of variables declaration//GEN-END:variables
}
