/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Swing;

import java.awt.Color;

/**
 *
 * @author felip
 */
public class P1 extends javax.swing.JPanel {
    public static String playerName;    
    
    public P1(String playerName) {
        this.playerName = playerName;
        String introduction = "Lucas es un gato que vive en un bosque muy \npeculiar, le llaman 'El pozo'. A veces recorrer \neste raro lugar le resulta muy complicado, asi \nque Lucas esta decidido en comprarse un \ncarro todoterreno. \n" + this.playerName + ", \n¡Acompaña a Lucas en esta aventura!";
        initComponents();
        introTxt.setText(introduction);
        Main.paintImage(backgroundImg, new int[]{1024, 768} , "src/main/java/View/Images/pozo.png");
        Main.paintImage(lucasImg, new int[]{180, 300}, "src/main/java/View/Images/lucas.png");
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTxt = new javax.swing.JLabel();
        continueBtn = new javax.swing.JButton();
        lucasImg = new javax.swing.JLabel();
        introTxt = new javax.swing.JTextArea();
        backgroundImg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleTxt.setFont(new java.awt.Font("Informal Roman", 0, 70)); // NOI18N
        titleTxt.setForeground(new java.awt.Color(0, 255, 0));
        titleTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTxt.setText("La travesia de Lucas");
        add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 570, 96));

        continueBtn.setText("Continuar");
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });
        add(continueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 250, 60));
        add(lucasImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 180, 300));

        introTxt.setEditable(false);
        introTxt.setBackground(new Color(0, 0, 0, 1));
        introTxt.setColumns(20);
        introTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        introTxt.setForeground(new java.awt.Color(255, 255, 255));
        introTxt.setRows(5);
        introTxt.setText("Lucas es un gato que vive en un bosque muy \npeculiar, le llaman “El Pozo”. A veces recorrer \neste raro lugar le resulta muy complicado, así \nque Lucas está decidido en comprarse un \ncarro todoterreno.  \nJugador, ¡Acompaña a Lucas en esta aventura!");
        introTxt.setBorder(null);
        add(introTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, 170));

        backgroundImg.setMaximumSize(new java.awt.Dimension(1024, 768));
        backgroundImg.setPreferredSize(new java.awt.Dimension(1024, 768));
        add(backgroundImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));
    }// </editor-fold>//GEN-END:initComponents

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
        P2 p2 = new P2();
        Main.showPanel(p2);
    }//GEN-LAST:event_continueBtnActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JButton continueBtn;
    private javax.swing.JTextArea introTxt;
    private javax.swing.JLabel lucasImg;
    private javax.swing.JLabel titleTxt;
    // End of variables declaration//GEN-END:variables
}
