/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Swing;

import java.awt.Color;

/**
 *
 * @author felip
 */
public class P3 extends javax.swing.JPanel {

    public P3() {
        initComponents();
        Main.paintImage(backgroundImg, new int[]{1024, 768} , "src/main/java/View/Images/pozo.png");
        Main.paintImage(serpentinaImg, new int[]{280, 250}, "src/main/java/View/Images/serpentina.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        continueBtn = new javax.swing.JButton();
        titleTxt = new javax.swing.JLabel();
        txt = new javax.swing.JTextArea();
        serpentinaImg = new javax.swing.JLabel();
        backgroundImg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        continueBtn.setText("Continuar");
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });
        add(continueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 250, 60));

        titleTxt.setFont(new java.awt.Font("Informal Roman", 0, 70)); // NOI18N
        titleTxt.setForeground(new java.awt.Color(0, 255, 0));
        titleTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTxt.setText("Encuentro inesperado");
        add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 720, 96));

        txt.setEditable(false);
        txt.setBackground(new Color(0, 0, 0, 1));
        txt.setColumns(20);
        txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setRows(5);
        txt.setText("La tranquilidad pronto se desvaneció. \nLucas dio un salto al ver a Serpentina.\nEsta serpiente, vieja amiga de Lucas, \nse desliza silenciosamente por el\nbosque, ¡siempre logra asustarlo! \nSerpentina rie a carcajadas sin importarle\nque Lucas casi se infarta. Pobrecito :(. \nParece que desconociera su \naterradora apariencia.");
        txt.setBorder(null);
        add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 350, 220));
        add(serpentinaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 280, 250));
        add(backgroundImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));
    }// </editor-fold>//GEN-END:initComponents

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
        P4 p4 = new P4();
        Main.showPanel(p4);
    }//GEN-LAST:event_continueBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JButton continueBtn;
    private javax.swing.JLabel serpentinaImg;
    private javax.swing.JLabel titleTxt;
    private javax.swing.JTextArea txt;
    // End of variables declaration//GEN-END:variables
}
