/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Swing;

import java.awt.Color;

/**
 *
 * @author felip
 */
public class P4 extends javax.swing.JPanel {

    /**
     * Creates new form P4
     */
    public P4() {
        initComponents();
        txt.setText("Luego de que volviera el alma de Lucas,\n Serpentina cuenta la razón de su llegada.\nNecesita ayuda.\nLucas y " + P1.playerName + " deben subir a la cima de \nun arbol para ayudar a localizar su comida.\n¡Serpentina tiene mucha hambre, ayudala!");
        Main.paintImage(backgroundImg, new int[]{1024, 768}, "src/main/java/View/Images/pozo.png");
        Main.paintImage(lucasImg, new int[]{180, 300}, "src/main/java/View/Images/lucas.png");
        Main.paintImage(serpentinaImg, new int[]{230, 250}, "src/main/java/View/Images/serpentina.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTxt = new javax.swing.JLabel();
        txt = new javax.swing.JTextArea();
        lucasImg = new javax.swing.JLabel();
        serpentinaImg = new javax.swing.JLabel();
        continueBtn = new javax.swing.JButton();
        backgroundImg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleTxt.setFont(new java.awt.Font("Informal Roman", 0, 70)); // NOI18N
        titleTxt.setForeground(new java.awt.Color(0, 255, 0));
        titleTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTxt.setText("Importante misión");
        add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 720, 96));

        txt.setEditable(false);
        txt.setBackground(new Color(0, 0, 0, 1));
        txt.setColumns(20);
        txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setRows(5);
        txt.setText("Luego de que volviera el alma de Lucas, \nSerpentina cuenta la razón de su llegada.\nNecesita ayuda.\nLucas y jugador deben subir a la cima de \nun arbol para ayudar a localizar su comida.\n¡Serpentina tiene mucha hambre, ayudala!");
        txt.setBorder(null);
        add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 350, 150));
        add(lucasImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 180, 300));
        add(serpentinaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 230, 250));

        continueBtn.setText("Continuar");
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });
        add(continueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 250, 60));
        add(backgroundImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));
    }// </editor-fold>//GEN-END:initComponents

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
        P5 p5 = new P5();
        Main.showPanel(p5);
    }//GEN-LAST:event_continueBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JButton continueBtn;
    private javax.swing.JLabel lucasImg;
    private javax.swing.JLabel serpentinaImg;
    private javax.swing.JLabel titleTxt;
    private javax.swing.JTextArea txt;
    // End of variables declaration//GEN-END:variables
}
