/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Swing;

/**
 *
 * @author felip
 */
public class P5 extends javax.swing.JPanel {

    GamePanel snakeGame;
    public static int score;
    
    public P5() {
        initComponents();
        Main.paintImage(backgroundImg, new int[]{1024, 768}, "src/main/java/View/Images/pozo.png");
        
        snakeGame = new GamePanel();
        snakeGame.setSize(500, 500);
        gameFrame.add(snakeGame);
        focusGameframe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retryBtn = new javax.swing.JButton();
        gameFrame = new javax.swing.JInternalFrame();
        txt2 = new javax.swing.JLabel();
        continueBtn = new javax.swing.JButton();
        txt1 = new javax.swing.JLabel();
        backgroundImg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        retryBtn.setText("Reintentar");
        retryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retryBtnActionPerformed(evt);
            }
        });
        add(retryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 250, 60));

        gameFrame.setBorder(null);
        gameFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        gameFrame.setVisible(true);

        javax.swing.GroupLayout gameFrameLayout = new javax.swing.GroupLayout(gameFrame.getContentPane());
        gameFrame.getContentPane().setLayout(gameFrameLayout);
        gameFrameLayout.setHorizontalGroup(
            gameFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gameFrameLayout.setVerticalGroup(
            gameFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(gameFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 520, 540));
        focusGameframe();

        txt2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt2.setText("Usa las flechas para moverte");
        add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 330, 110));

        continueBtn.setText("Continuar");
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });
        add(continueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 250, 60));

        txt1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt1.setText("¡Consigue al menos 5 puntos!");
        add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 330, 110));
        add(backgroundImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));
    }// </editor-fold>//GEN-END:initComponents

    private void retryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retryBtnActionPerformed
        if (snakeGame.isLost) {
            snakeGame.resetStatus();
            snakeGame.play();
            focusGameframe();
        }
    }//GEN-LAST:event_retryBtnActionPerformed

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
        if (!snakeGame.isLost) {
            score = snakeGame.score;
            P6 p6 = new P6();
            Main.showPanel(p6);
            
        }
    }//GEN-LAST:event_continueBtnActionPerformed

    private void focusGameframe() {
        try {
                gameFrame.setSelected(true);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JButton continueBtn;
    private javax.swing.JInternalFrame gameFrame;
    private javax.swing.JButton retryBtn;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    // End of variables declaration//GEN-END:variables
}
