/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Swing;

import java.awt.Color;

/**
 *
 * @author felip
 */
public class P6 extends javax.swing.JPanel {

    public P6() {
        initComponents();
        Main.paintImage(backgroundImg, new int[]{1024, 768}, "src/main/java/View/Images/pozo.png");
        Main.paintImage(serpentinaImg, new int[]{300, 300}, "src/main/java/View/Images/serpentina.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTxt = new javax.swing.JLabel();
        serpentinaImg = new javax.swing.JLabel();
        continueBtn = new javax.swing.JButton();
        txt = new javax.swing.JTextArea();
        backgroundImg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleTxt.setFont(new java.awt.Font("Informal Roman", 0, 70)); // NOI18N
        titleTxt.setForeground(new java.awt.Color(0, 255, 0));
        titleTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTxt.setText("Concesionario");
        add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 720, 96));
        add(serpentinaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 300, 300));

        continueBtn.setText("Continuar");
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });
        add(continueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 250, 60));

        txt.setEditable(false);
        txt.setBackground(new Color(0, 0, 0, 1));
        txt.setColumns(20);
        txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setRows(5);
        txt.setText("Serpentina está muy agradecida por la \nayuda. Para agradecerles, los guia hacía el\nconcesionario \"El Minino\". ¡Por fin!\nLucas está muy feliz.");
        txt.setBorder(null);
        add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 350, 150));
        add(backgroundImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));
    }// </editor-fold>//GEN-END:initComponents

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
        P7 p7 = new P7();
        Main.showPanel(p7);
    }//GEN-LAST:event_continueBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JButton continueBtn;
    private javax.swing.JLabel serpentinaImg;
    private javax.swing.JLabel titleTxt;
    private javax.swing.JTextArea txt;
    // End of variables declaration//GEN-END:variables
}
