/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Swing;
import Control.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felip
 */
public class P8 extends javax.swing.JPanel {
    
    private String[] selection;

    private DefaultTableModel model;
    
    public P8(String[] selection) {
        initComponents();
        this.selection = selection;
        Main.paintImage(backgroundImg, new int[]{1024, 768}, "src/main/java/View/Images/cars.png");
        
        model = new DefaultTableModel();

        model.addColumn("Marca");
        model.addColumn("Referencia");
        model.addColumn("Precio");
        
        model.addRow(selection);
        
        table.setModel(model);
        table.setDefaultEditor(Object.class, null);
        
        User player = new User(P1.playerName, new Car(selection), P5.score);
        JsonWriter jWriter = new JsonWriter("Data/players.json");
        jWriter.insertObject(player);
        jWriter.saveJson();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filepathSelector = new javax.swing.JFileChooser();
        titleTxt = new javax.swing.JLabel();
        continueBtn = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        billBtn = new javax.swing.JButton();
        backgroundImg = new javax.swing.JLabel();

        filepathSelector.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        filepathSelector.setApproveButtonText("Generar");
        filepathSelector.setApproveButtonToolTipText("Generar factura");
        filepathSelector.setDialogTitle("Seleccionar ruta de la factura");
        filepathSelector.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        filepathSelector.setToolTipText("Selecciona la ruta de la factura");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleTxt.setFont(new java.awt.Font("Informal Roman", 0, 70)); // NOI18N
        titleTxt.setForeground(new java.awt.Color(0, 255, 0));
        titleTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTxt.setText("Has seleccionado:");
        add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 720, 96));

        continueBtn.setText("Continuar");
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });
        add(continueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, 250, 60));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Marca", "Referencia", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(42);
        table.getTableHeader().setResizingAllowed(false);
        table.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
        }

        add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, 70));

        billBtn.setText("Generar factura");
        billBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billBtnActionPerformed(evt);
            }
        });
        add(billBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 170, 60));
        add(backgroundImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));
    }// </editor-fold>//GEN-END:initComponents

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
        P9 p9 = new P9();
        Main.showPanel(p9);
    }//GEN-LAST:event_continueBtnActionPerformed

    private void billBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billBtnActionPerformed
        int result = filepathSelector.showSaveDialog(this);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            BillWriter bw = new BillWriter(filepathSelector.getSelectedFile().getAbsolutePath() + "/factura_vehiculo.pdf");
            bw.generateBill(new User(P1.playerName, new Car(selection), P5.score));
        }
    }//GEN-LAST:event_billBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JButton billBtn;
    private javax.swing.JButton continueBtn;
    private javax.swing.JFileChooser filepathSelector;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    private javax.swing.JLabel titleTxt;
    // End of variables declaration//GEN-END:variables
}
