/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Swing;

import java.awt.Color;

/**
 *
 * @author felip
 */
public class P9 extends javax.swing.JPanel {
    
    private boolean isDancing = false;
    
    public P9() {
        initComponents();
        Main.paintImage(backgroundImg, new int[]{1024, 768}, "src/main/java/View/Images/pozo.png");
        Main.paintImage(lucasImg, new int[]{200, 320}, "src/main/java/View/Images/lucas.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTxt = new javax.swing.JLabel();
        txt = new javax.swing.JTextArea();
        lucasImg = new javax.swing.JLabel();
        danceBtn = new javax.swing.JButton();
        backgroundImg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleTxt.setFont(new java.awt.Font("Informal Roman", 0, 70)); // NOI18N
        titleTxt.setForeground(new java.awt.Color(0, 255, 0));
        titleTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTxt.setText("FELICIDADES");
        add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 720, 96));

        txt.setEditable(false);
        txt.setBackground(new Color(0, 0, 0, 1));
        txt.setColumns(20);
        txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setRows(5);
        txt.setText("Lucas está muy feliz con su nueva \nadquisición. Gracias por ayudar a Lucas.\nHa sido una corta pero emocionante\naventura, espero la hayas disfrutado.\nMira como Lucas baila con mucha emocion.\n¡Has que Lucas baile!");
        txt.setBorder(null);
        add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 350, 170));
        add(lucasImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 200, 320));

        danceBtn.setText("Bailar");
        danceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                danceBtnActionPerformed(evt);
            }
        });
        add(danceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, 140, 60));
        add(backgroundImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));
    }// </editor-fold>//GEN-END:initComponents

    private void danceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_danceBtnActionPerformed
        if (!isDancing) {
            dance();
        } else {
            Main.paintImage(lucasImg, new int[]{200, 320}, "src/main/java/View/Images/lucas.png");
        }
        isDancing = !isDancing;
    }//GEN-LAST:event_danceBtnActionPerformed

    public void dance() {
        Main.paintImage(lucasImg, new int[]{200, 320}, "src/main/java/View/Images/lucas.gif");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JButton danceBtn;
    private javax.swing.JLabel lucasImg;
    private javax.swing.JLabel titleTxt;
    private javax.swing.JTextArea txt;
    // End of variables declaration//GEN-END:variables
}
